### ISSUE TITLE
ADD ANIME CARDS NOW :rage:

### ISSUE THREAD

**Issue by buster77fa** [Gideon9212/Server_Script_CDB#11]
add anime cards now :rage:

**Comment by Gideon9212** [comment]
So demanding. Did you know that percy's client has core functions that no other client has to handle most of the anime card effects? (And even with that, some don't work?)
Consider the work and stuff that has to be done first, and what we would have to do to add anime cards before making such a comment again. Next comment like this, and I will block you from the repo.
