### ISSUE TITLE
master peace(21377582) can't tribute a S/T and a opponent monster

### ISSUE THREAD

**Issue by Doca343** [Gideon9212/Server_Script_CDB#14]
Probably a problem with all true dracos but master peace confirmed, you can't tribute summon using a S/T and a opponent monster whe you use something like monarch stormforth, probably something in the the function that selects the materials, saying that you can only select things you control

**Comment by Gideon9212** [comment]
Should be fixed here.
https://github.com/Gideon9212/Server_Script_CDB/compare/2b328571ecda...006a4bb1c807
Fix by Andre.
