### ISSUE TITLE
Symphonic warrior piaano and drumss(31826057 and 94331452)

### ISSUE THREAD

**Issue by Doca343** [Gideon9212/Server_Script_CDB#17]
both don't change attributes and types

**Comment by AndreOliveiraMendes** [comment]
do you have a replay of it not working?

**Comment by AndreOliveiraMendes** [comment]
ok, updated they on 
https://github.com/Gideon9212/Server_Script_CDB/commit/7a3d692a6cf8733db556d4929cdde01ad0eafd42
https://github.com/Gideon9212/Server_Script_CDB/commit/087b836aa640186a8bcfd717b558a9f38b1b1364
should be fine now
